// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/auth.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BesuAuthExtension authenticates a tx signed with Ethereum private keys
type BesuAuthExtension struct {
}

func (m *BesuAuthExtension) Reset()         { *m = BesuAuthExtension{} }
func (m *BesuAuthExtension) String() string { return proto.CompactTextString(m) }
func (*BesuAuthExtension) ProtoMessage()    {}
func (*BesuAuthExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a8fdae18e2be49a, []int{0}
}
func (m *BesuAuthExtension) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BesuAuthExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BesuAuthExtension.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BesuAuthExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BesuAuthExtension.Merge(m, src)
}
func (m *BesuAuthExtension) XXX_Size() int {
	return m.Size()
}
func (m *BesuAuthExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_BesuAuthExtension.DiscardUnknown(m)
}

var xxx_messageInfo_BesuAuthExtension proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BesuAuthExtension)(nil), "extension.types.BesuAuthExtension")
}

func init() { proto.RegisterFile("types/auth.proto", fileDescriptor_0a8fdae18e2be49a) }

var fileDescriptor_0a8fdae18e2be49a = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x3d, 0x4e, 0xc4, 0x30,
	0x10, 0x85, 0x9d, 0x86, 0x62, 0x1b, 0x7e, 0xab, 0x15, 0x72, 0x41, 0x9f, 0x4c, 0xc1, 0x09, 0x58,
	0x09, 0x89, 0x33, 0xd0, 0x8d, 0xbd, 0x8e, 0x6d, 0x29, 0xf1, 0x44, 0x9e, 0xb1, 0x04, 0xb7, 0xe0,
	0x58, 0x29, 0x53, 0x52, 0x42, 0x72, 0x11, 0x84, 0x23, 0xe8, 0x3e, 0xbd, 0xf7, 0xf4, 0xf4, 0x1d,
	0xae, 0xe4, 0x7d, 0x72, 0x0c, 0x58, 0x24, 0x74, 0x53, 0x26, 0xa1, 0x9b, 0x4b, 0xf7, 0x26, 0x2e,
	0x71, 0xa4, 0xd4, 0xd5, 0xee, 0x78, 0xef, 0x89, 0xfc, 0xe0, 0x00, 0xa7, 0x08, 0x98, 0x12, 0x09,
	0x4a, 0xa4, 0xc4, 0xfb, 0xfc, 0x78, 0xe7, 0xc9, 0x53, 0x45, 0xf8, 0xa5, 0x3d, 0x7d, 0xb8, 0x3d,
	0x5c, 0x9f, 0x1c, 0x97, 0xa7, 0x22, 0xe1, 0xf9, 0xef, 0xee, 0xd4, 0xcf, 0xdf, 0x5a, 0xcd, 0xab,
	0x6e, 0x96, 0x55, 0x37, 0x5f, 0xab, 0x6e, 0x3e, 0x36, 0xad, 0x96, 0x4d, 0xab, 0xcf, 0x4d, 0xab,
	0xd7, 0x17, 0x1f, 0x25, 0x14, 0xd3, 0x59, 0x1a, 0xe1, 0x8c, 0x82, 0x36, 0x60, 0x4c, 0x03, 0x1a,
	0xe8, 0xd1, 0xe4, 0x68, 0x5b, 0xe3, 0xb8, 0xb4, 0x36, 0x13, 0x73, 0x7b, 0x76, 0x23, 0x81, 0xa5,
	0x24, 0x19, 0xad, 0x30, 0xfc, 0x0b, 0x43, 0x15, 0x36, 0x17, 0xd5, 0xe1, 0xf1, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x9e, 0x8f, 0x69, 0xa2, 0xdc, 0x00, 0x00, 0x00,
}

func (m *BesuAuthExtension) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BesuAuthExtension) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BesuAuthExtension) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintAuth(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuth(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BesuAuthExtension) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovAuth(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuth(x uint64) (n int) {
	return sovAuth(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BesuAuthExtension) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BesuAuthExtension: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BesuAuthExtension: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipAuth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuth(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuth
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuth
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuth
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuth        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuth          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuth = fmt.Errorf("proto: unexpected end of group")
)
